#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,                     tServoNormal)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,                     tServoNormal)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,                     tServoNormal)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,                     tServoNormal)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,                     tServoNormal)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,                     tServoNormal)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                    - Servo Control by NXT Motor -                                      *|
|*                                        ROBOTC on NXT + TETRIX                                          *|
|*                                                                                                        *|
|*  This program simply sweeps the servo back and forth.  Servo Change Rate can be changed by changing    *|
|*  'delta'.  (0 = max servo speed, # > 0 = how many servo positions to move per update (every 20ms).     *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  Be sure to attach a servo somewhere on the robot.                                               *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port 1                  none                TETRIX Controller   TETRIX                              *|
|*    Port 1 - Chan. 1        servo1              std. Servo          The servo that you wish to test.    *|
\*---------------------------------------------------------------------------------------------------4246-*/
task main()
{
  int delta = 2;                        // Create int 'delta' to the be Servo Change Rate.

  while(true)
  {
    servoChangeRate[servo5] = delta;          // Slow the Servo Change Rate down to only 'delta' positions per update.

    if(ServoValue[servo5] < 90)              // If servo1 is closer to 0 (than 180):
    {
      while(ServoValue[servo5] < 180)               // While the ServoValue of servo1 is less than 180:
      {
        servo[servo5] = 180;                              // Move servo1 to position to 180.
      }
    }

    wait1Msec(1000);                          // Wait 1 second.

    if(ServoValue[servo5] >= 90)             // If servo1 is closer to 145 (than 0):
    {
      while(ServoValue[servo5] > 0)                 // While the ServoValue of servo1 is greater than 0:
      {
        servo[servo5] = 0;                                // Move servo1 to position to 0.
      }
    }

    wait1Msec(1000);                          // Wait 1 second.

    servoChangeRate[servo4] = delta;          // Slow the Servo Change Rate down to only 'delta' positions per update.

    if(ServoValue[servo4] < 135)              // If servo1 is closer to 0 (than 145):
    {
      while(ServoValue[servo4] < 210)               // While the ServoValue of servo1 is less than 145:
      {
        servo[servo4] = 210;                              // Move servo1 to position to 145.
      }
    }

    wait1Msec(1000);                          // Wait 1 second.

    if(ServoValue[servo4] >= 135)             // If servo1 is closer to 145 (than 0):
    {
      while(ServoValue[servo4] > 60)                 // While the ServoValue of servo1 is greater than 0:
      {
        servo[servo4] = 60;                                // Move servo1 to position to 0.
      }
    }

    wait1Msec(1000);                          // Wait 1 second.
  }

















}
