#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyro,           sensorI2CCustomFastSkipStates)
#pragma config(Sensor, S3,     leftIR,         sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     rightIR,        sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     frontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rearLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     rearRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     armMotor,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    leftServo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    rightServo,           tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Include file to "handle" the Bluetooth messages.
#include "ImprovedJoystick.c"

// Forward declaration of routine used by Gyro
void disableMotors();

//
// Forward declarations
//
void moveArm();
void showDisplay();
int expoJoystick(int eJoy);

void disableMotors() {
    motor[frontLeft] = 0;
    motor[frontRight] = 0;
    motor[rearLeft] = 0;
    motor[rearRight] = 0;
}

void initializeRobot() {
    disableMotors();

    motor[armMotor] = 0;
    nMotorEncoder[armMotor] = 0;
}

task main() {
    initializeRobot();

    while (true) {
        // Get current joystick buttons and analog movements
        getJoystickSettings(joystick);

        // Display all the information on the screen
        showDisplay();

        // move the arm
        moveArm();

        EndTimeSlice();
    }
}

void showDisplay() {
}

// Keep track of arm state so we can keep the arm from
// drooping when we stop it.
int oldArmPower = 0;
int stopArmPos = 0;
int stopArmPower = 0;
long stopArmPowerChangeTime = 0;
const int ARM_STOP_POWER_CHANGE_INCREMENT_TIME = 20;

bool feedBtnWasPressed = false;
bool feedbackActive = false;
void moveArm() {
    // Enable/disable the arm-holding feedback cod
    bool feedBtn = joy1Btn(3);
    if (feedBtn && !feedBtnWasPressed)
        feedbackActive = !feedbackActive;
    feedBtnWasPressed = feedBtn;

    // Use the Y joystick to move the arm, but only give it at most
    // half-power.
    int armPower = expoJoystick(joystick.joy1_y1);
    armPower /= 2;

    // Move *much* slower when going down
    if (armPower < 0)
        armPower /= 3;

    // Are we actively moving the arm?
    if (armPower != 0) {
        // Remember what the user-supplied power was.
        oldArmPower = armPower;

        // Reset the stopArmPower
        stopArmPower = 0;
    } else if (feedbackActive) {
        // No user-supplied arm power.  Attempt to hold the arm at the
        // stopped position using the encoder for feedback.
        long now = nPgmTime;

        // Check to see if we just stopped (the arm was just moving and
        // is now stopped).
        if (oldArmPower != 0) {
            // Reset the encoder to indicate this is the 'stop' position
            // and give us a bit of time let the arm settle down before
            // we check to see if it's moved.
            nMotorEncoder[armMotor] = 0;
            stopArmPos = 0;
            stopArmPower = 0;
            stopArmPowerChangeTime = now + 2 * ARM_STOP_POWER_CHANGE_INCREMENT_TIME;
        } else if (now > stopArmPowerChangeTime) {
            // Check to see if the arm is still moving?  If so, add some
            // power in the opposite direction to try and stop it.
            int armPos = nMotorEncoder[armMotor];
            if (abs(armPos - stopArmPos) != 0) {
                if (armPos < stopArmPos)
                    stopArmPower++;
                else
                    stopArmPower--;
                // We've made an adjustment, reset the state so we can
                // recheck this again to see if it's moving.  This time
                // we'll check a bit more quickly.
                stopArmPos = armPos;
                stopArmPowerChangeTime = now + ARM_STOP_POWER_CHANGE_INCREMENT_TIME;
            } else if (stopArmPower != 0 &&
                       now > stopArmPowerChangeTime + 20 * ARM_STOP_POWER_CHANGE_INCREMENT_TIME) {
                // If the arm is stopped with power on for some time,
                // turn off the motor completely to avoid burning up
                // motors and save the battery.  Note, if the arm moves
                // again, the code should notice and and stop the
                // movement, and cause this code to 'pulse' the motor to
                // hold it in place.
                stopArmPower = 0;
            }
            nxtDisplayString(5, "RAS=%d", armPos);
        }
        oldArmPower = armPower;
        armPower = stopArmPower;

        // Feedback to user
        nxtDisplayString(2, "UAP=%d", oldArmPower);
        nxtDisplayString(3, "SAP=%d", stopArmPower);
        nxtDisplayString(4, "Pos=%d", stopArmPos);
    }
    nxtDisplayString(0, "FB=%d", feedbackActive);
    nxtDisplayString(1, "Pow=%d", armPower);

    // Set the motor power
    motor[armMotor] = armPower;
}

// http://www.chiefdelphi.com/forums/showthread.php?p=921992
const float SENSITIVITY = 0.7;
int expoJoystick(int eJoy)
{
    // convert the joystick inputs to a floating point number
    // between -1 and +1
    float floatJoy = (float)eJoy / 127.0;
    float result = SENSITIVITY * pow(floatJoy, 3) +
                   (1 - SENSITIVITY) * floatJoy;

    // Convert the number back to a motor power, which is between -100
    // and 100.
    return (int)(100.0 * result);
}
