#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyro,           sensorI2CCustomFastSkipStates)
#pragma config(Sensor, S3,     leftIR,         sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     rightIR,        sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     frontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rearLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     rearRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     armMotor,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    leftServo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    rightServo,           tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Include file to "handle" the Bluetooth messages.
#include "ImprovedJoystick.c"

// Forward declaration of routine used by Gyro
void disableMotors();

//
// Forward declarations
//
void moveArm();
int expoJoystick(int eJoy);

void disableMotors() {
    motor[frontLeft] = 0;
    motor[frontRight] = 0;
    motor[rearLeft] = 0;
    motor[rearRight] = 0;
}

void initializeRobot() {
    disableMotors();

    motor[armMotor] = 0;
    nMotorEncoder[armMotor] = 0;
}

task main() {
    initializeRobot();

    while (true) {
        // Get current joystick buttons and analog movements
        getJoystickSettings(joystick);

        // move the arm
        moveArm();

        EndTimeSlice();
    }
}

// Keep track of arm state so we can keep the arm from drooping when we
// stop it.
int oldArmPower = 0;
int stopArmPower = 0;
long stopArmPowerChangeTime = 0;
const int ARM_STOP_POWER_CHANGE_INCREMENT_TIME = 20;

bool feedBtnWasPressed = false;
bool feedbackActive = false;
void moveArm() {
    // Enable/disable the arm-holding feedback code so we can compare
    // behavior of the robot with/without the code.
    bool feedBtn = joy1Btn(3);
    if (feedBtn && !feedBtnWasPressed)
        feedbackActive = !feedbackActive;
    feedBtnWasPressed = feedBtn;

    // Use the Y joystick to move the arm, but only give it at most
    // half-power.
    int userArmPower = expoJoystick(joystick.joy1_y1);
    userArmPower /= 2;

    // Move *much* slower when going down
    if (userArmPower < 0)
        userArmPower /= 3;

    // Determine the actual Arm power to use.
    int actualArmPower = 0;
    if (userArmPower != 0) {
        // The user is actively moving the arm (supplying joystick
        // power), so use that power for controlling the arm motor.
        actualArmPower = userArmPower;
    } else if (feedbackActive) {
        // No user-supplied arm power.  Attempt to hold the arm at the
        // stopped position using the encoder for feedback.
        long now = nPgmTime;

        // Check to see if we just stopped (the arm was just moving and
        // is now being stopped).
        if (oldArmPower != 0) {
            // Maybe we don't need any power, so let's hope the arm
            // doesn't droop.
            stopArmPower = 0;

            // Reset the encoder to indicate this is the 'stop' position
            // and give us a bit of time than normal to let the arm
            // settle down before we check to see if it's moved.
            nMotorEncoder[armMotor] = 0;
            stopArmPowerChangeTime = now + 2 * ARM_STOP_POWER_CHANGE_INCREMENT_TIME;
        } else if (now > stopArmPowerChangeTime) {
            // Check to see if the arm has moved.  If so, add some
            // power in the opposite direction to try and counteract it.
            int armPos = nMotorEncoder[armMotor];
            if (abs(armPos) > 0) {
                // It's moving, so add some power in the opposite direction
                if (armPos < 0)
                    stopArmPower++;
                else
                    stopArmPower--;

                // We've made an adjustment, reset the position and
                // setup to recheck again shortly to see if it's still
                // moving.
                nMotorEncoder[armMotor] = 0;
                stopArmPowerChangeTime = now + ARM_STOP_POWER_CHANGE_INCREMENT_TIME;
            } else if (stopArmPower != 0 &&
                       now > stopArmPowerChangeTime + 20 * ARM_STOP_POWER_CHANGE_INCREMENT_TIME) {
                // The arm has not moved in some time, but we are
                // actively using the motor to keep it from moving.  To
                // avoid burning up motors and save the battery turn off
                // the motor completely.  Note, if the arm starts to
                // move again, the code should notice immediately (since
                // we don't reset stopArmPowerChangeTime) and work to
                // stop the movement.  This behavior will end up causing
                // the motor to 'pulse' at whatever frequency necessary
                // to hold it in place.
                stopArmPower = 0;
            }
        }
        actualArmPower = stopArmPower;
    }
    // Feedback to user
    nxtDisplayString(0, "FB=%d", feedbackActive);
    nxtDisplayString(1, "Pow=%d", userArmPower);
    nxtDisplayString(2, "SAP=%d", stopArmPower);

    // Set the motor power
    motor[armMotor] = actualArmPower;

    // Remember the user-supplied armPower so we can step in when power
    // is first disabled.
    oldArmPower = userArmPower;
}

// http://www.chiefdelphi.com/forums/showthread.php?p=921992
const float SENSITIVITY = 0.7;
int expoJoystick(int eJoy)
{
    // convert the joystick inputs to a floating point number
    // between -1 and +1
    float floatJoy = (float)eJoy / 127.0;
    float result = SENSITIVITY * pow(floatJoy, 3) +
                   (1 - SENSITIVITY) * floatJoy;

    // Convert the number back to a motor power, which is between -100
    // and 100.
    return (int)(100.0 * result);
}
