#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Motor,  motorA,          Nxtrightmotor, tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          Nxtleftmotor,  tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     Leftmotor,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Rightmotor,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Ballmotor,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Armmotor,      tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    Rightservo,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    Leftservo,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Motor,  mtr_S1_C2_2,     Armmotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//TJoystick joystick;

task main()
{
 int threshold = 20;

 while (true)
  {
    getJoystickSettings(joystick);
      if(abs(joystick.joy1_y2) > threshold)
          motor[Rightmotor] = joystick.joy1_y2;
        else
          motor[Rightmotor] = 0;

      if(abs(joystick.joy1_y1) > threshold)
          motor[Leftmotor] = -joystick.joy1_y1;
        else
          motor[Leftmotor] = 0;

      if(abs(joystick.joy2_y2) > threshold)
         motor[Nxtleftmotor] = joystick.joy2_y2;
        else
          motor[Nxtleftmotor] = 0;

      if(abs(joystick.joy2_y1) > threshold)
          motor[Nxtrightmotor] = joystick.joy2_y1;
        else
          motor[Nxtrightmotor] = 0;

      if(joy1Btn(8))
        motor[Ballmotor] = -100;
      else
        motor[Ballmotor] = 0;

      if(joy2Btn(8))
        motor[Armmotor] = 30;
      else
        motor[Armmotor] = 0;

      if(joy2Btn(6))
      {
        servo[Rightservo] = 116;
        servo[Leftservo] = 128;
      }
      else
      {
        servo[Rightservo] = 0;
        servo[Leftservo] = 255;
      }

  }
}
