#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     Leftmotor,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Rightmotor,    tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
const float move_1_ft = 1600;

void move1foot(float numfeet)
{
  float movetime=abs(numfeet) * move_1_ft;
  if (numfeet > 0)
  {
   motor[Leftmotor] = 10 ;
   motor[Rightmotor] = 10 ;
 }else if (numfeet < 0)
 {
   motor[Leftmotor] = -10 ;
   motor[Rightmotor] = -10 ;
}
  wait1Msec(movetime);

  motor[Leftmotor] = 0 ;
  motor[Rightmotor] = 0 ;
}
const float turnright360 = 2700;

void turnright(int degrees)
{
    float movetime=turnright360 * abs(degrees) / 360;
  if (degrees > 0)
  {
   motor[Leftmotor] = 20 ;
   motor[Rightmotor] = -20 ;
 }else if (degrees < 0)
 {
   motor[Leftmotor] = -20 ;
   motor[Rightmotor] = 20 ;
}
  wait1Msec(movetime);

  motor[Leftmotor] = 0 ;
  motor[Rightmotor] = 0 ;
}

task main()
{

  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////
  ////                                                   ////
  ////    Add your robot specific autonomous code here.  ////
  ////                                                   ////
  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////


  move1foot(1);
  wait1Msec(1000);
 // move1foot(-1.5);
 // wait1Msec(1000);
 // move1foot(2);
  //wait1Msec(1000);
  turnright(-180);
  wait1Msec(1000);
  move1foot(1);
  wait1Msec(1000);
  turnright(360);
  while (true)
  {}
}
