#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Motor,  motorA,          Nxtrightmotor, tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          Nxtleftmotor,  tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     Leftmotor,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Rightmotor,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Ballmotor,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Armmotor,      tmotorNormal, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    Rightservo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    Leftservo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    Rotatorservo,         tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    clawservo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int transmission = 100;

task main()
{
    int threshold = 20;
    bool btnUWP = false;
    bool btnDWP = false;

    servo[Rotatorservo] = 0;
    servo[Rightservo] = 0;
    servo[Leftservo] = 255;
    servo[clawservo] = 0;

    while (true)
    {
        // Up is Positive

        // nxtDisplayString(0, "encoder=%d", nMotorEncoder[Armmotor]);
        getJoystickSettings(joystick);
        if (abs(joystick.joy1_y2) > threshold)
            motor[Rightmotor] = joystick.joy1_y2 * transmission / 100;
        else
            motor[Rightmotor] = 0;

        if (abs(joystick.joy1_y1) > threshold)
            motor[Leftmotor] = -joystick.joy1_y1 * transmission / 100;
        else
            motor[Leftmotor] = 0;

//        if (abs(joystick.joy2_y2) > threshold)
//            motor[Nxtleftmotor] = joystick.joy2_y2;
//        else
//            motor[Nxtleftmotor] = 0;

//        if (abs(joystick.joy2_y1) > threshold)
//            motor[Nxtrightmotor] = joystick.joy2_y1;
//        else
//            motor[Nxtrightmotor] = 0;

        if (joy1Btn(8))
            motor[Ballmotor] = 100;
        else if (joy1Btn(6))
            motor[Ballmotor] = -100;
        else
            motor[Ballmotor] = 0;

//        int armPos = nMotorEncoder[Armmotor];

//        if (joy2Btn(6) && armPos < 720)
//            motor[Armmotor] = 80;
//        else if(joy2Btn(8) && armPos > 0)
//            motor[Armmotor] = -10;
//        else
//            motor[Armmotor] = 0;

        if (joy2Btn(6))
            motor[Armmotor] = 80;
        else if (joy2Btn(8))
            motor[Armmotor] = -10;
        else
            motor[Armmotor] = 0;

//        nxtDisplayString(1, "LS=%d", ServoValue(Leftservo));
//        nxtDisplayString(0, "RS=%d", ServoValue(Rotatorservo));
//        nxtDisplayString(2, "CS=%d", ServoValue(clawservo));

        if (joy1Btn(7))
        {
            servo[Rightservo] = 116;
            servo[Leftservo] = 128;
        }

        if (joy1Btn(5))
        {
            servo[Rightservo] = 0;
            servo[Leftservo] = 255;
        }

        if (joy2Btn(4))
        {
            int location = ServoValue(Rotatorservo) + 3;
            if (location > 250)
                location = 250;
            servo[Rotatorservo] = location;
        }
        else if (joy2Btn(1))
        {
            int location = ServoValue(Rotatorservo) - 3;
            if (location < 0)
                location = 0;
            servo[Rotatorservo] = location;
        }

//        nxtDisplayString(1, "%d", joy2Btn(2));

        if (joy2Btn(2))
        {
            wait1Msec(5);
            int clawPos = ServoValue(clawservo) + 3;
            if (clawPos > 255)
                clawPos = 255;
            servo[clawservo] = clawPos;
        }
        else if (joy2Btn(3))
        {
            wait1Msec(5);
            int clawPos = ServoValue(clawservo) - 3;
            if (clawPos < 0)
                clawPos = 0;
            servo[clawservo] = clawPos;
        }

        if (joystick.joy1_TopHat == 0 && !btnUWP)
        {
            if (transmission+20 <= 100)
                transmission+=20;
        }

        if (joystick.joy1_TopHat == 4 && !btnDWP)
        {
            if (transmission - 20 > 0)
                transmission -= 20;
        }

        btnUWP = (joystick.joy1_TopHat == 0);
        btnDWP = (joystick.joy1_TopHat == 4);
    }
}
